describe("Completar formulario", () => {
    it("pruebita", () => {
        cy.visit("https://demoqa.com/")
        cy.get("svg[baseProfile='tiny']")
            .click()
        cy.get("div[class='element-list collapse show']")
            .click()
        cy.get("input[id='firstName']")
            .type("Carlos Alberto")
        cy.get("input[id='lastName']")
            .type("Ccanto Torres")
        cy.get("input[id='userEmail']")
            .type("carloscctorres@gmail.com")
        cy.get('#gender-radio-1').parent().click()
        cy.get("input[id='userNumber']")
            .type("11111111")
    })
})